name: Deploy to GitHub Pages on Merge

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: "**/*.md"

      - name: Build and run Golang program
        run: |
          go build -o generate-html main.go
          ./generate-html

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./generated

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
