name: Deploy to GitHub Pages on Merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: '**/*.md'

      - name: Build and run Golang program
        run: |
          go build -o generate-html main.go
          ./generate-html

